version: "3.0"
services:
  client:
    build: "."
    command: ["npm", "start"]
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
